using System;

namespace AuthenticationService.Application.IdentityUsers.Responses
{
    public class TokenResponse
    {
        /// <summary>
        /// Token generated by the user
        /// </summary>
        public string Token { get; set; }
        /// <summary>
        /// Expiration date of the token
        /// </summary>
        public DateTime Expiration { get; set; }
    }
}
